//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_TheKeeper.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheKeeperPRODataBaseEntities : DbContext
    {
        private static TheKeeperPRODataBaseEntities _context;
        public TheKeeperPRODataBaseEntities()
            : base("name=TheKeeperPRODataBaseEntities")
        {
        }
        /// <summary>
        /// Получение контекста базы данных
        /// </summary>
        /// <returns>
        /// Возращает значение контекста базы данных
        /// </returns>
        public static TheKeeperPRODataBaseEntities GetContext()
        {
            if (_context == null)
                _context = new TheKeeperPRODataBaseEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<ListOFVisitor> ListOFVisitors { get; set; }
        public virtual DbSet<PurposeOfVisit> PurposeOfVisits { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StatusRequest> StatusRequests { get; set; }
        public virtual DbSet<TypeRequest> TypeRequests { get; set; }
    }
}
