//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_TheKeeper.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int PurposeOfVisitCode { get; set; }
        public int DivisionCode { get; set; }
        public string FullNameEmployeeDivision { get; set; }
        public string SurName { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Organization { get; set; }
        public string Note { get; set; }
        public System.DateTime DateBirth { get; set; }
        public string PassportSeries { get; set; }
        public string PassportID { get; set; }
        public byte[] VisitorPhoto { get; set; }
        public int StatusRequestCode { get; set; }
        public int TypeRequestCode { get; set; }
        public byte[] AttachedDocument { get; set; }
        public Nullable<int> ListOfVisitorsCode { get; set; }
        public Nullable<bool> BlackList { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> DateDeparture { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual ListOFVisitor ListOFVisitor { get; set; }
        public virtual PurposeOfVisit PurposeOfVisit { get; set; }
        public virtual StatusRequest StatusRequest { get; set; }
        public virtual TypeRequest TypeRequest { get; set; }
    }
}
